language: java
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

script:
  - mvn clean install jacoco:report

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov

after_success:
  - codecov
